sudo: required
services:
  - docker
env:
  global:
    - GIT_SHA=$(git rev-parse HEAD)
before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t jfdv/react-test -f ./react-app/Dockerfile.dev ./react-app
script:
  - docker run -e CI=true jfdv/react-test npm run test
deploy:
  provider: script
  script: bash ./travis-deploy.sh
  on:
    branch: master
