version: '3'
services:
    possgress:
        image: postgres:latest
        environment:
            - POSTGRES_PASSWORD=postgres_password
    reddis:
        image: redis:latest
    ekspress:
        depends_on: 
            - possgress
            - reddis
        build:
            dockerfile: Dockerfile.dev
            context: express-server
        volumes:
            - /app/node_modules
            - ./express-server:/app
        environment:
            - REDIS_HOST=reddis
            - REDIS_PORT=6379
            - PG_USER=postgres
            - PG_HOST=possgress
            - PG_DATABASE=postgres
            - PG_PASSWORD=postgres_password
            - PG_PORT=5432
    reackt:
        stdin_open: true
        build:
            dockerfile: Dockerfile.dev
            context: react-app
        volumes:
            - /app/node_modules
            - ./react-app:/app
    reddis-worker:
        build:
            dockerfile: Dockerfile.dev
            context: redis-worker
        volumes:
            - /app/node_modules
            - ./redis-worker:/app
        environment:
            - REDIS_HOST=reddis
            - REDIS_PORT=6379
    engineks:
        depends_on: 
            - ekspress
            - reackt
        restart: always
        build:
            dockerfile: Dockerfile.dev
            context: nginx-router
        ports:
            - '1337:80'
