apiVersion: skaffold/v1beta2
kind: Config
build:
  local:
    push: false
  artifacts:
    - image: jfdv/multipass-react-app
      context: react-app
      docker:
        dockerfile: Dockerfile.dev
      sync:
        '**/*.js': .
        '**/*.css': .
        '**/*.html': .
    - image: jfdv/multipass-express-server
      context: express-server
      docker:
        dockerfile: Dockerfile.dev
      sync:
        '**/*.js': .
    - image: jfdv/multipass-redis-worker
      context: redis-worker
      docker:
        dockerfile: Dockerfile.dev
      sync:
        '**/*.js': .
deploy:
  kubectl:
    manifests:
      - k8s/client-deployment.yaml
      - k8s/server-deployment.yaml
      - k8s/worker-deployment.yaml
      - k8s/client-clusterfuck-service.yaml
      - k8s/server-clusterfuck-service.yaml
